apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{beta}}backend-volume
  namespace: salvemundi
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{storage}}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{beta}}backend-volume-claim
  namespace: salvemundi
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{beta}}backend
  namespace: salvemundi
spec:
  selector:
    matchLabels:
      app: {{beta}}salvemundi-backend
      tier: backend
  replicas: 1
  template:
    metadata:
      name: {{beta}}salvemundi-backend
      namespace: salvemundi
      labels:
        app: {{beta}}salvemundi-backend
        tier: backend
    spec:
      volumes:
        - name: {{beta}}backend-storage
          persistentVolumeClaim:
            claimName: {{beta}}backend-volume-claim
      containers:
      - name: {{beta}}salvemundi-backend
        image: svsalvemundi/backend:{{samu_backend_version}}
        volumeMounts:
          - mountPath: {{storage}}
            name: {{beta}}backend-storage
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: DB_HOST
          value: "{{db_host}}"
        - name: DB_PORT
          value: "{{db_port}}"
        - name: DB_USER
          value: "{{db_user}}"
        - name: DB_PASSWORD
          value: "{{db_password}}"
        - name: DB_NAME
          value: "{{db_name}}"
        - name: SERVER_PORT
          value: "1337"
        - name: JWT_SECRET
          value: "{{jwt_secret}}"
        - name: MOLLIE_API_KEY
          value: "{{mollie_key}}"
        - name: REDIRECT_URL
          value: "https://{{beta_site_link}}salvemundi.nl/home/"
        - name: MOLLIE_WEBHOOK_URL
          value: "https://{{beta}}api.salvemundi.nl/webhook/"
        - name: SENDGRID_PASS
          value: "{{sendgrid_password}}"
        - name: SENDGRID_USER
          value: "{{sendgrid_user}}"
        - name: STORAGE_PATH
          value: "{{storage}}"
        - name: RABOBANK_URL
          value: "{{rabobank_url}}"
        - name: RABOBANK_CLIENT_ID
          value: "{{rabobank_client_id}}"
        - name: RABOBANK_CLIENT_SECRET
          value: "{{rabobank_client_secret}}"
        - name: RABOBANK_CERTIFICATE_KEY_ID
          value: "{{rabobank_certificate_key_id}}"
        - name: RABOBANK_PRIVATE_KEY_PATH
          value: "{{rabobank_private_key_path}}"
        - name: RABOBANK_CERTIFICATE_PATH
          value: "{{rabobank_certificate_path}}"
        ports:
        - containerPort: 1337

---

apiVersion: v1
kind: Service
metadata:
  name: {{beta}}backend-service
  namespace: salvemundi
spec:
  type: NodePort
  selector:
    app: {{beta}}salvemundi-backend
    tier: backend
  ports:
    - port: 1337
